POST http://localhost:8000/api/v1/books/
Content-Type: application/json

{
    "title": "Clean Code",
    "author": "Robert Martin",
    "count_pages": 500,
    "year": 2021
}


###

GET http://localhost:8000/api/v1/books/

###

GET http://localhost:8000/api/v1/books/3

###

DELETE http://localhost:8000/api/v1/books/1

###
PUT http://localhost:8000/api/v1/books/5
Content-Type: application/json

{    
    "id": 5,
    "title": "Architecture Code",
    "author": "Other",
    "year": 2025,
    "pages": 340
}