# Набор тестов для эндпоинтов которые можно запустить
# в VSCode с помощью плагина  REST Client
# Найти можно по идентификатору: humao.rest-client
# Tunder Client не позволяет свободно импортировать-экспортировать записи,
# поэтому используем этот плагин. Он тоже хорош :-)


# Создаем книгу
POST http://localhost:8000/api/v1/books/
Content-Type: application/json

{
    "title": "Clean Code",
    "author": "Robert Martin",
    "count_pages": 500,
    "year": 2021
}


###

# Получаем список книг
GET http://localhost:8000/api/v1/books/

###

# Получаем одну книгу по ее ИД
GET http://localhost:8000/api/v1/books/2

###

# Удаляем книгу
DELETE http://localhost:8000/api/v1/books/3

###

# Обновляем поля в данных о книге
PUT http://localhost:8000/api/v1/books/4
Content-Type: application/json

{    
    "id": 5,
    "title": "Clean Architecture",
    "author": "Robert Martin",
    "year": 2025,
    "pages": 340
}

###