# Набор тестов для эндпоинтов которые можно запустить
# в VSCode с помощью плагина  REST Client
# Найти можно по идентификатору: humao.rest-client
# Tunder Client не позволяет свободно импортировать-экспортировать записи,
# поэтому используем этот плагин. Он тоже хорош :-)


# 1. Создаем продавца
#TODO # ВАЖНО!!!  email должен быть уникаьным иначе сервер упадет - это надо обработать
# TODO при создании некоррекного продавца (не уникальный мейл), id  все равно увеличивается
# Пришлось добавить try/exept чтобы обратобать падение сервера при повторном использовани мейла для создания селлера
POST http://localhost:8000/api/v1/seller
Content-Type: application/json

{
    "first_name": "John",
    "last_name": "Doe",
    "email": "2john.doe@example.com",
    "password": "securepassword123"
}


###


# 2. Получаем список всех продавцов
GET http://localhost:8000/api/v1/seller

###

# 3. Получаем данные о конкретном продавце (замените {seller_id} на реальный ID)
GET http://localhost:8000/api/v1/seller/5


###

# 4. Обновляем данные продавца (замените {seller_id} на реальный ID)
# email и password должны быть именно этго селлера, которого изменяем
PUT http://localhost:8000/api/v1/seller/30
Content-Type: application/json

{
    "first_name": "Jonathan",
    "last_name": "Doe",
    "email": "2john.doe@example.com",
    "password": "securepassword123"
}

###

# 5. Удаляем продавца (замените {seller_id} на реальный ID)
DELETE http://localhost:8000/api/v1/seller/3

###

# 6. Создаем книгу, связанную с продавцом (замените seller_id на реальный ID)
# TODO падает сервер
POST http://localhost:8000/api/v1/books/
Content-Type: application/json

{
    "title": "Clean Code",
    "author": "Robert Martin",
    "count_pages": 500,
    "year": 2021,
    "seller_id": 30
}


###


# 7. Получаем список всех книг
GET http://localhost:8000/api/v1/books/

###

# 8. Получаем одну книгу по ее ID (замените {book_id} на реальный ID)
GET http://localhost:8000/api/v1/books/15

###

# 9. Обновляем данные книги (замените {book_id} на реальный ID)
PUT http://localhost:8000/api/v1/books/15w
Content-Type: application/json

{
    "id": 1,
    "title": "Clean Architecture",
    "author": "Robert Martin",
    "year": 2025,
    "pages": 340,
    "seller_id": 1
}

###

# 10. Удаляем книгу (замените {book_id} на реальный ID)
DELETE http://localhost:8000/api/v1/books/6