[pytest]
testpaths = src/tests # папки до тестов
pythonpath = .  # путь до интерпритатора приложения , см в той же папке где pytest
; addopts = -ra --verbosity=2 --rootdir=${workspaceFolder}/src --color=yes
# Доп опции: --verbosity=2 : максимально подробные логи
# --rootdir=${workspaceFolder}/src  : корневая директория где находится приложение
# --color=yes цветные логи

